### ISSUE TITLE
HDF5-DIAG: Error detected in HDF5

### ISSUE THREAD

**Issue by tommylees112** [esowc/ml_drought#63]
```python
/ouce-home/staff/smit0136/.conda/envs/ed_37/lib/python3.7/site-packages/xarray/core/nanops.py:161: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis=axis, dtype=dtype)
HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 139654709049088:
  #000: H5F.c line 509 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1400 in H5F__open(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #002: H5Fint.c line 1615 in H5F_open(): unable to lock the file
    major: File accessibilty
    minor: Unable to open file
  #003: H5FD.c line 1640 in H5FD_lock(): driver lock request failed
    major: Virtual File Layer
    minor: Can't update object
  #004: H5FDsec2.c line 939 in H5FD_sec2_lock(): file locking disabled on this file system (use HDF5_USE_FILE_LOCKING environment variable to override), errno = 38, error message = 'Function not implemented'
    major: File accessibilty
    minor: Bad file ID accessed
Traceback (most recent call last):
  File "/ouce-home/staff/smit0136/.conda/envs/ed_37/lib/python3.7/site-packages/xarray/backends/file_manager.py", line 167, in acquire
    file = self._cache[self._key]
  File "/ouce-home/staff/smit0136/.conda/envs/ed_37/lib/python3.7/site-packages/xarray/backends/lru_cache.py", line 42, in __getitem__
    value = self._cache[key]
KeyError: [<function _open_netcdf4_group at 0x7f037c9a8a60>, ('/ouce-home/data_not_backed_up/satellite/chirps_v20/chirps-v2.0.1981.days_p05.nc', CombinedLock([<SerializableLock: 5325e251-9c6d-4dc7-ae7c-f96c7cac0cf1>, <SerializableLock: af2c6612-4016-433d-9f5c-7512ee52e6bb>])), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('group', None), ('persist', False))]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "awash_regions_risk.py", line 107, in <module>
    pr_daily_in = xr.open_mfdataset("/ouce-home/data_not_backed_up/satellite/chirps_v20/*.nc",combine='by_coords',engine='netcdf4')
  File "/ouce-home/staff/smit0136/.conda/envs/ed_37/lib/python3.7/site-packages/xarray/backends/api.py", line 766, in open_mfdataset
    datasets = [open_(p, **open_kwargs) for p in paths]
  File "/ouce-home/staff/smit0136/.conda/envs/ed_37/lib/python3.7/site-packages/xarray/backends/api.py", line 766, in <listcomp>
    datasets = [open_(p, **open_kwargs) for p in paths]
  File "/ouce-home/staff/smit0136/.conda/envs/ed_37/lib/python3.7/site-packages/xarray/backends/api.py", line 420, in open_dataset
    filename_or_obj, group=group, lock=lock, **backend_kwargs)
  File "/ouce-home/staff/smit0136/.conda/envs/ed_37/lib/python3.7/site-packages/xarray/backends/netCDF4_.py", line 360, in open
    return cls(manager, lock=lock, autoclose=autoclose)
  File "/ouce-home/staff/smit0136/.conda/envs/ed_37/lib/python3.7/site-packages/xarray/backends/netCDF4_.py", line 319, in __init__
    self.format = self.ds.data_model
  File "/ouce-home/staff/smit0136/.conda/envs/ed_37/lib/python3.7/site-packages/xarray/backends/netCDF4_.py", line 364, in ds
    return self._manager.acquire().value
  File "/ouce-home/staff/smit0136/.conda/envs/ed_37/lib/python3.7/site-packages/xarray/backends/file_manager.py", line 173, in acquire
    file = self._opener(*self._args, **kwargs)
  File "/ouce-home/staff/smit0136/.conda/envs/ed_37/lib/python3.7/site-packages/xarray/backends/netCDF4_.py", line 252, in _open_netcdf4_group
    ds = nc4.Dataset(filename, mode=mode, **kwargs)
  File "netCDF4/_netCDF4.pyx", line 2291, in netCDF4._netCDF4.Dataset.__init__
  File "netCDF4/_netCDF4.pyx", line 1855, in netCDF4._netCDF4._ensure_nc_success
OSError: [Errno -101] NetCDF: HDF error: b'/ouce-home/data_not_backed_up/satellite/chirps_v20/chirps-v2.0.1981.days_p05.nc'

```

**Comment by tommylees112** [comment]
```
export HDF5_USE_FILE_LOCKING=‘FALSE'
```
